### ISSUE TITLE
Need docker inside action container

### ISSUE THREAD

**Issue by RuiLoureiro** [ScottBrenner/aws-cdk-action#21]
Hey there, I'm trying to run this action on a stack that includes the [PythonFunction](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-python.PythonFunction.html) construct, which requires the machine where you run `cdk synth` to have docker installed.

This aws-cdk issue exposes the same problem: https://github.com/aws/aws-cdk/issues/9348

Here is the error I'm getting:
```
2021-04-07T13:00:04.6745024Z Traceback (most recent call last):
2021-04-07T13:00:04.6745616Z   File "app.py", line 10, in <module>
2021-04-07T13:00:04.6746496Z     CardiaCdkStack(app, f"{env}-cardia-cdk")
2021-04-07T13:00:04.6747588Z   File "/usr/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
2021-04-07T13:00:04.6748372Z     inst = super().__call__(*args, **kwargs)
2021-04-07T13:00:04.6749123Z   File "/github/workspace/cardia_cdk/cardia_cdk_stack.py", line 32, in __init__
2021-04-07T13:00:04.6750027Z     input_bucket, lambda_sign_url = setup_signed_url(self, removal_policy)
2021-04-07T13:00:04.6750962Z   File "/github/workspace/cardia_cdk/signed_url.py", line 21, in setup_signed_url
2021-04-07T13:00:04.6751831Z     lambda_sign_url = _lambda_py.PythonFunction(
2021-04-07T13:00:04.6752914Z   File "/usr/lib/python3.8/site-packages/jsii/_runtime.py", line 83, in __call__
2021-04-07T13:00:04.6753695Z     inst = super().__call__(*args, **kwargs)
2021-04-07T13:00:04.6754754Z   File "/usr/lib/python3.8/site-packages/aws_cdk/aws_lambda_python/__init__.py", line 253, in __init__
2021-04-07T13:00:04.6755919Z     jsii.create(PythonFunction, self, [scope, id, props])
2021-04-07T13:00:04.6757066Z   File "/usr/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 275, in create
2021-04-07T13:00:04.6757949Z     response = self.provider.create(
2021-04-07T13:00:04.6759136Z   File "/usr/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 344, in create
2021-04-07T13:00:04.6760173Z     return self._process.send(request, CreateResponse)
2021-04-07T13:00:04.6761392Z   File "/usr/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 326, in send
2021-04-07T13:00:04.6762453Z     raise JSIIError(resp.error) from JavaScriptError(resp.stack)
2021-04-07T13:00:04.6763400Z jsii.errors.JSIIError: spawnSync docker ENOENT
```

**Comment by ScottBrenner** [comment]
https://github.com/aws/aws-cdk/issues/9348#issuecomment-678440912 mentions a potential fix, although implementing the "build script" portion - specifically the `docker run` volume mounting - in this Action might be a bit tricky, probably with https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainervolumes.

**Comment by ScottBrenner** [comment]
https://github.com/ScottBrenner/aws-cdk-action/pull/54#issuecomment-2052729919
